### ISSUE TITLE
bug: After changing settings in a network I get a white screen and restart doesn't fix issue

### ISSUE THREAD

**Issue by bodleytunes** [dec0dOS/zero-ui#34]
# Bug Report

**ZeroUI version:** 
latest

**Current behavior:**

I modify a network then press to return to main page but get a white screen

**Expected behavior:**

should return to list of networks (home page)

**Steps to reproduce:**

was messing around in the networks page, possibly I entered some bad data for the ip range not sure

**Related code:**

not sure
possibly this as found a 500 internal server error
```
Node.js v17.1.0
undefined
/app/backend/app.js:72
  res.status(500).json({ error: "500 Internal server error" });
      ^

TypeError: res.status is not a function
    at /app/backend/app.js:72:7
    at Layer.handle [as handle_request] (/app/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/backend/node_modules/express/lib/router/index.js:317:13)
    at /app/backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/backend/node_modules/express/lib/router/index.js:335:12)
    at next (/app/backend/node_modules/express/lib/router/index.js:275:10)
    at compression (/app/backend/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/app/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/backend/node_modules/express/lib/router/index.js:317:13)
    at /app/backend/node_modules/express/lib/router/index.js:284:7
```

**Other information:**

**Comment by bodleytunes** [comment]
it looks like all the networks have gone when it "flashes" up for a split second.  I'm sure I've had this before when I entered some network data or changed a subnet.

![white-screen-of-death](https://user-images.githubusercontent.com/619239/142762515-90fe0783-42e9-484c-ae95-da1dd6e5a69d.gif)

**Comment by dec0dOS** [comment]
Hello, @bodleytunes. You should check the ZeroUI logs on the server and on the client side.

**Comment by bodleytunes** [comment]
OK I will check and get back

**Comment by bodleytunes** [comment]
Where do I find the zu controller logs?  Docker logs shows nothing and I can't see anything in the container?

**Comment by bodleytunes** [comment]
The zu-main container just seems to show these logs

```
GET /app/static/js/runtime-main.1e458087.js 200 1.189 ms - -
GET /app/static/js/main.a25a804b.chunk.js 200 0.858 ms - -
GET /app/static/js/8.dd99f694.chunk.js 200 0.871 ms - -
GET /app/static/media/roboto-latin-400-normal.4673b453.woff2 200 1.014 ms - 15688
GET /app/favicon.ico 200 0.757 ms - -
GET /app/manifest.json 200 0.723 ms - 226
POST /auth/login 200 310.388 ms - 44
GET /app/ 304 1.286 ms - -
GET /app/static/css/8.bf512090.chunk.css 304 0.537 ms - -
GET /app/static/css/main.52e70a0d.chunk.css 304 0.412 ms - -
GET /app/static/js/runtime-main.1e458087.js 304 0.501 ms - -
GET /app/static/js/8.dd99f694.chunk.js 304 0.278 ms - -
GET /app/static/js/main.a25a804b.chunk.js 304 0.340 ms - -
GET /app/static/media/roboto-latin-400-normal.4673b453.woff2 304 0.511 ms - -
GET /api/network 200 6.418 ms - -
GET /app/favicon.ico 200 0.783 ms - -
GET /app/manifest.json 304 0.536 ms - -
GET /app/ 304 0.317 ms - -
GET /app/static/css/8.bf512090.chunk.css 304 0.452 ms - -
GET /app/static/css/main.52e70a0d.chunk.css 304 0.388 ms - -
GET /app/static/js/runtime-main.1e458087.js 304 0.526 ms - -
GET /app/static/js/8.dd99f694.chunk.js 304 0.314 ms - -
GET /app/static/js/main.a25a804b.chunk.js 304 0.417 ms - -
GET /api/network 200 5.822 ms - -
GET /app/favicon.ico 200 0.539 ms - -
GET /app/manifest.json 304 0.326 ms - -
GET /app' 404 0.462 ms - 25
GET /favicon.ico 404 0.442 ms - 25
GET /app/ 304 0.382 ms - -
GET /app/static/css/8.bf512090.chunk.css 304 0.372 ms - -
GET /app/static/css/main.52e70a0d.chunk.css 304 0.424 ms - -
GET /app/static/js/runtime-main.1e458087.js 304 0.334 ms - -
GET /app/static/js/8.dd99f694.chunk.js 304 0.503 ms - -
GET /app/static/js/main.a25a804b.chunk.js 304 0.386 ms - -
GET /app/manifest.json 304 2.057 ms - -
GET /api/network 200 7.309 ms - -
GET / 302 0.456 ms - 52
GET /app/ 304 1.216 ms - -
GET /app/static/css/8.bf512090.chunk.css 304 0.672 ms - -
GET /app/static/css/main.52e70a0d.chunk.css 304 0.539 ms - -
GET /app/static/js/runtime-main.1e458087.js 304 0.595 ms - -
GET /app/static/js/8.dd99f694.chunk.js 304 0.417 ms - -
GET /app/static/js/main.a25a804b.chunk.js 304 0.308 ms - -
GET /api/network 200 6.458 ms - -
GET /app/manifest.json 304 0.295 ms - -
GET /app/app 404 1.010 ms - 25
GET /app/app--- 404 0.733 ms - 25
GET /app' 404 0.306 ms - 25
GET /app 301 0.422 ms - 173
GET /app/ 200 0.643 ms - 768
GET /app/ 304 0.349 ms - -
GET /app/static/css/8.bf512090.chunk.css 304 0.564 ms - -
GET /app/static/css/main.52e70a0d.chunk.css 304 0.798 ms - -
GET /app/static/js/runtime-main.1e458087.js 304 0.339 ms - -
GET /app/static/js/8.dd99f694.chunk.js 304 0.305 ms - -
GET /app/static/js/main.a25a804b.chunk.js 304 0.299 ms - -
GET /api/network 200 6.823 ms - -
GET /app/static/media/roboto-latin-400-normal.4673b453.woff2 304 0.457 ms - -
GET /app/manifest.json 304 0.299 ms - -
GET /app/ 304 0.313 ms - -
GET /app/static/css/8.bf512090.chunk.css 304 0.441 ms - -
GET /app/static/css/main.52e70a0d.chunk.css 304 0.317 ms - -
GET /app/static/js/runtime-main.1e458087.js 304 0.270 ms - -
GET /app/static/js/8.dd99f694.chunk.js 304 0.277 ms - -
GET /app/static/js/main.a25a804b.chunk.js 304 0.271 ms - -
GET /app/static/media/roboto-latin-400-normal.4673b453.woff2 304 3.241 ms - -
GET /api/network 200 7.906 ms - -
GET /app/manifest.json 304 0.391 ms - -
GET /app' 404 1.177 ms - 25
GET / 302 7.602 ms - 52
GET /app 301 2.382 ms - 173
GET /app/ 304 1.823 ms - -
GET /app/static/css/8.bf512090.chunk.css 304 1.021 ms - -
GET /app/static/css/main.52e70a0d.chunk.css 304 0.689 ms - -
GET /app/static/js/8.dd99f694.chunk.js 304 0.799 ms - -
GET /app/static/js/runtime-main.1e458087.js 304 1.014 ms - -
GET /app/static/js/main.a25a804b.chunk.js 304 1.149 ms - -
GET /app/static/media/roboto-latin-400-normal.4673b453.woff2 304 8.104 ms - -
GET /api/network 200 17.435 ms - -
GET /app/favicon.ico 304 0.544 ms - -
GET /app/manifest.json 304 0.549 ms - -
GET / 302 0.345 ms - 26
GET /app 301 0.410 ms - 173
GET /app/ 200 5.079 ms - 768
GET / 302 0.282 ms - 26
GET /app 301 0.378 ms - 173
GET /app/ 200 1.084 ms - 768
GET / 302 0.240 ms - 26
GET /app 301 0.387 ms - 173
GET /app/ 200 0.984 ms - 768
GET / 302 0.383 ms - 26
GET / 302 1.283 ms - 26
GET /app 301 0.421 ms - 173
GET /app/ 200 0.807 ms - 768
GET / 302 0.283 ms - 26
GET /app 301 0.415 ms - 173
GET /app/ 200 0.646 ms - 768
GET /favicon.ico 404 0.514 ms - 25
GET / 302 0.312 ms - 26
GET / 302 0.277 ms - 26
GET /app 301 0.471 ms - 173
GET /app/ 200 0.734 ms - 768

```

**Comment by bodleytunes** [comment]
I can also see a db file in the docker volume  which is Json and shows all the networks.

**Comment by bodleytunes** [comment]
ok I managed to get it back by going directly to the network edit page for that particular problem network, then I deleted all the routes and the ip ranges and added them automatically and it worked.

There must have been something that I entered that it didn't like.
